---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redmine
  name: redmine
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - image: redmine:4.1.1
          name: redmine
          ports:
            - containerPort: 3000
          env:
            - name: REDMINE_DB_POSTGRES
              value: database
            - name: REDMINE_DB_USERNAME
              value: redmine
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: REDMINE_DB_PASSWORD
            - name: REDMINE_DB_DATABASE
              value: redmine
            - name: REDMINE_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: REDMINE_SECRET_KEY_BASE
